### PR TITLE
add initial asset registry api Swagger docs

### PR DESCRIPTION
**Pull request by kiafaldorius**
Although I've included both the YAML and JSON formats, you should pick one format and stick to it. (They can be converted as needed.)

The YAML format may be easier for you to make edits from, as it is more human readable.

### CODE REVIEW

**Comment by dockerymick** [comment]
@kiafaldorius Thank you so much for creating this PR and providing your recommendations! I appreciate you! I have been looking into [Hosting Swagger in GitHub pages](https://github.com/peter-evans/swagger-github-pages); based on the instructions, it seems like it would be best to go with the YAML. Here is my [PR](https://github.com/agstack/agstack-website/pull/7) where I am making changes. Can you also review that PR to provide recommendations

**Comment by dockerymick** [comment]
@kiafaldorius Do you mind if I move forward with removing the JSON file from this PR or do you prefer to remove it?

**Comment by dockerymick** [comment]
CC: @Aanish97

**Comment by kiafaldorius** [comment]
@dockerymick You're welcome to make any changes you want to this branch.

**Comment by dockerymick** [comment]
@kiafaldorius thanks for your patience and confirmation! I decided to go with the JSON file for now and will move forward with merging this PR.

**Review by dockerymick — APPROVED** [review]

**Pull request merged**
